/*
 * Academic License - for use in teaching, academic research, and meeting
 * course requirements at degree granting institutions only.  Not for
 * government, commercial, or other organizational use.
 * File: utils_quatYawCorrectionJac1.c
 *
 * MATLAB Coder version            : 24.2
 * C/C++ source code generated on  : 04-May-2025 14:15:47
 */

/* Include Files */
#include "yawCorrectionJac.h"
#include <math.h>

/* Function Definitions */
/*
 * quatYawCorrectionJac1
 *     qJ = quatYawCorrectionJac1(IN1,IN2)
 *
 * Arguments    : const float in1[7]
 *                const float in2[3]
 *                float qJ[7][3]
 * Return Type  : void
 */
/* Function Definitions */
/*
 * quatYawCorrectionJac
 *     stateJm = quatYawCorrectionJac(IN1,IN2)
 *
 * Arguments    : const float in1[4]
 *                const float in2[3]
 *                float stateJm[4][3]
 * Return Type  : void
 */
void quatYawCorrectionJac(const float in1[4], const float in2[3],
                                 float stateJm[4][3])
{
  float fv[12];
  float t106;
  float t2;
  float t24;
  float t25;
  float t26;
  float t28;
  float t29;
  float t3;
  float t30;
  float t31;
  float t32;
  float t36;
  float t37;
  float t39;
  float t4;
  float t48;
  float t5;
  float t7;
  float t71;
  float t8;
  float t83_tmp;
  float t84;
  float t85_tmp_tmp;
  float t95;
  int i;
  int i1;
  int i2;
  /*     This function was generated by the Symbolic Math Toolbox version 24.2.
   */
  /*     08-Jul-2025 21:21:27 */
  t2 = in1[0] * in1[1];
  t3 = in1[0] * in1[2];
  t4 = in1[1] * in1[3];
  t5 = in1[2] * in1[3];
  t7 = in1[1] * in1[1];
  t8 = in1[2] * in1[2];
  t24 = in1[0] * in1[0] + in1[3] * in1[3];
  t25 = t7 + t8;
  t26 = t2 + t5;
  t28 = t3 - t4;
  t29 = t2 * 2.0F + t5 * 2.0F;
  t30 = 1.0F / t24;
  t31 = 1.0F / t25;
  t36 = 1.0F / sqrtf(t24);
  t37 = 1.0F / sqrtf(t25);
  t32 = t3 * 2.0F - t4 * 2.0F;
  t39 = 1.0F / (t24 + t25);
  t4 = ((in2[0] * t2 + in2[1] * t3) + in2[0] * t5) - in2[1] * t4;
  t3 = acosf(t39 * ((-t7 - t8) + t24)) / 2.0F;
  t25 = sinf(t3);
  t48 = cosf(t3);
  t8 = t48 * t48;
  t24 = t25 * t25;
  t71 = t26 * t28 * t30 * t39 + t29 * t30 * t31 * t32 * t24 / 4.0F;
  t2 = (in2[2] * t48 + in2[1] * t29 * t36 * t37 * t25 / 2.0F) -
       in2[0] * t32 * t36 * t37 * t25 / 2.0F;
  t83_tmp = t32 * t36 * t37 * t25;
  t7 = (t26 * t30 * t39 * t4 +
        t48 * (in2[0] * t48 + in2[2] * t32 * t36 * t37 * t25 / 2.0F)) +
       t83_tmp * t2 / 2.0F;
  t84 = t7 * t7;
  t3 = t28 * t30 * t39 * t4 +
       t48 * (in2[1] * t48 - in2[2] * t29 * t36 * t37 * t25 / 2.0F);
  t85_tmp_tmp = t29 * t36 * t37 * t25;
  t25 = t85_tmp_tmp * t2;
  t4 = t3 - t25 / 2.0F;
  t5 = 1.0F / t7;
  t36 = 1.0F / t84;
  t95 = 1.0F / (t84 + t4 * t4);
  t2 = -(atan2f(t3 - t25 * 0.5F, t7) / 2.0F);
  t106 = t85_tmp_tmp * t48 * t5 + t83_tmp * t48 * t4 * t36;
  t25 = t30 * t31;
  t37 = t71 * t5 -
        ((t26 * t26 * t30 * t39 + t8) - t25 * (t32 * t32) * t24 / 4.0F) * t4 *
            t36;
  t24 = ((t30 * (t28 * t28) * t39 + t8) - t25 * (t29 * t29) * t24 / 4.0F) * t5 -
        t71 * t4 * t36;
  t36 = cosf(t2 + 0.785398185F);
  t8 = sinf(t2 + 0.785398185F);
  t5 = t48 * t84 * t95;
  t7 = t5 * t8;
  fv[0] = t7 * t37 / 2.0F;
  t4 = t85_tmp_tmp * t84 * t95;
  t3 = t83_tmp * t84 * t95;
  t25 = t4 * t8;
  t2 = t3 * t36;
  fv[1] = t25 * t37 * -0.25F - t2 * t37 / 4.0F;
  t4 *= t36;
  t3 *= t8;
  fv[2] = t4 * t37 / 4.0F - t3 * t37 / 4.0F;
  t5 *= t36;
  fv[3] = t5 * t37 * -0.5F;
  fv[4] = t7 * t24 / 2.0F;
  fv[5] = t25 * t24 * -0.25F - t2 * t24 / 4.0F;
  fv[6] = t4 * t24 / 4.0F - t3 * t24 / 4.0F;
  fv[7] = t5 * t24 * -0.5F;
  fv[8] = t7 * t106 * -0.5F;
  fv[9] = t25 * t106 / 4.0F + t2 * t106 / 4.0F;
  fv[10] = t4 * t106 * -0.25F + t3 * t106 / 4.0F;
  fv[11] = t5 * t106 / 2.0F;
  i = 0;
  i1 = 0;
  for (i2 = 0; i2 < 12; i2++) {
    stateJm[i][i1] = fv[i2];
    i++;
    if (i > 3) {
      i = 0;
      i1++;
    }
  }
}

/* Function Definitions */
/*
 * quatYawCorrectionJacS
 *     stateJq = quatYawCorrectionJacS(IN1,IN2)
 *
 * Arguments    : const float in1[4]
 *                const float in2[3]
 *                float stateJq[16]
 * Return Type  : void
 */
void quatYawCorrectionJacS(const float in1[4], const float in2[3],
                                 float stateJq[16])
{
  float fv[16];
  float b_t335_tmp;
  float b_t338_tmp;
  float c_t335_tmp;
  float c_t338_tmp;
  float d_t335_tmp;
  float d_t338_tmp;
  float e_t335_tmp;
  float e_t338_tmp;
  float t10;
  float t11;
  float t119;
  float t12;
  float t120;
  float t122;
  float t123;
  float t129;
  float t129_tmp;
  float t13;
  float t132;
  float t132_tmp;
  float t134;
  float t134_tmp;
  float t135;
  float t135_tmp;
  float t15;
  float t16;
  float t170;
  float t171;
  float t2;
  float t212;
  float t213;
  float t213_tmp;
  float t214;
  float t214_tmp;
  float t215;
  float t215_tmp;
  float t216;
  float t216_tmp;
  float t264_tmp;
  float t265;
  float t266_tmp_tmp;
  float t267;
  float t278;
  float t279;
  float t298;
  float t3;
  float t300;
  float t335_tmp;
  float t336_tmp;
  float t338;
  float t338_tmp;
  float t34;
  float t35;
  float t36;
  float t37;
  float t38;
  float t39;
  float t4;
  float t40;
  float t41;
  float t42;
  float t43;
  float t44;
  float t45;
  float t46;
  float t47;
  float t48;
  float t49;
  float t5;
  float t51;
  float t52;
  float t53;
  float t58;
  float t6;
  float t7;
  float t73;
  float t75;
  float t8;
  float t83;
  float t9;
  float t90;
  float t91;
  float t92;
  int i;
  int i1;
  int i2;
  /*     This function was generated by the Symbolic Math Toolbox version 24.2.
   */
  /*     08-Jul-2025 21:21:23 */
  t2 = in2[0] * in1[0];
  t3 = in2[0] * in1[1];
  t4 = in1[0] * in2[1];
  t5 = in2[0] * in1[2];
  t6 = in2[1] * in1[1];
  t7 = in2[0] * in1[3];
  t8 = in2[1] * in1[2];
  t9 = in2[1] * in1[3];
  t10 = in1[0] * in1[1];
  t11 = in1[0] * in1[2];
  t12 = in1[1] * in1[3];
  t13 = in1[2] * in1[3];
  t15 = in1[1] * in1[1];
  t16 = in1[2] * in1[2];
  t34 = in1[0] * in1[0] + in1[3] * in1[3];
  t35 = t15 + t16;
  t36 = t3 + t8;
  t37 = t4 + t7;
  t38 = t10 + t13;
  t39 = t2 - t9;
  t40 = t5 - t6;
  t41 = t11 - t12;
  t42 = t10 * 2.0F + t13 * 2.0F;
  t43 = 1.0F / t34;
  t46 = 1.0F / sqrtf(t34);
  t47 = 1.0F / sqrtf(t35);
  t13 = (-t15 - t16) + t34;
  t44 = t43 * t43;
  t45 = t11 * 2.0F - t12 * 2.0F;
  t48 = powf(t46, 3.0F);
  t49 = powf(t47, 3.0F);
  t51 = 1.0F / (t34 + t35);
  t53 = ((in1[1] * t2 + in1[2] * t4) + in1[3] * t5) - in1[3] * t6;
  t52 = t51 * t51;
  t58 = in1[3] * t51 * 2.0F;
  t90 = in1[1] * t43 * t51 * t53;
  t91 = in1[2] * t43 * t51 * t53;
  t92 = in1[3] * t43 * t51 * t53;
  t10 = acosf(t51 * t13) / 2.0F;
  t119 = in1[1] * t51 * 2.0F + in1[1] * t52 * t13 * 2.0F;
  t120 = in1[2] * t51 * 2.0F + in1[2] * t52 * t13 * 2.0F;
  t73 = sinf(t10);
  t75 = cosf(t10);
  t122 = in1[0] * t51 * 2.0F - in1[0] * t52 * t13 * 2.0F;
  t123 = t58 - in1[3] * t52 * t13 * 2.0F;
  t10 = in2[0] * t75;
  t15 = in2[1] * t75;
  t83 = in2[2] * t75;
  t34 = 1.0F / sqrtf(-(t52 * (t13 * t13)) + 1.0F);
  t129_tmp = in1[0] * in2[2];
  t129 = t129_tmp * t46 * t47 * t73;
  t132_tmp = in1[1] * in2[2];
  t132 = t132_tmp * t46 * t47 * t73;
  t134_tmp = in2[2] * in1[2];
  t134 = t134_tmp * t46 * t47 * t73;
  t135_tmp = in2[2] * in1[3];
  t135 = t135_tmp * t46 * t47 * t73;
  t170 = t10 + in2[2] * t45 * t46 * t47 * t73 / 2.0F;
  t171 = t15 - in2[2] * t42 * t46 * t47 * t73 / 2.0F;
  t212 = (t83 + in2[1] * t42 * t46 * t47 * t73 / 2.0F) -
         in2[0] * t45 * t46 * t47 * t73 / 2.0F;
  t213_tmp = in1[0] * t46 * t47 * t73;
  t213 = t213_tmp * t212;
  t214_tmp = in1[1] * t46 * t47 * t73;
  t214 = t214_tmp * t212;
  t215_tmp = in1[2] * t46 * t47 * t73;
  t215 = t215_tmp * t212;
  t216_tmp = in1[3] * t46 * t47 * t73;
  t216 = t216_tmp * t212;
  t16 = in2[2] * t73 * t34;
  t35 = t45 * t46 * t47;
  t13 = t35 * t10 * t34;
  t11 = t42 * t46 * t47;
  t10 = t11 * t15 * t34;
  t278 = (((((t4 * t46 * t47 * t73 + t7 * t46 * t47 * t73) +
             t3 * t45 * t46 * t49 * t73 / 2.0F) -
            t6 * t42 * t46 * t49 * t73 / 2.0F) -
           t16 * t119 / 2.0F) +
          t10 * t119 / 4.0F) -
         t13 * t119 / 4.0F;
  t279 = (((((t2 * t46 * t47 * t73 + -t9 * t46 * t47 * t73) +
             t8 * t42 * t46 * t49 * t73 / 2.0F) -
            t5 * t45 * t46 * t49 * t73 / 2.0F) +
           t16 * t120 / 2.0F) +
          t13 * t120 / 4.0F) -
         t10 * t120 / 4.0F;
  t12 = (((((t3 * t46 * t47 * t73 + t8 * t46 * t47 * t73) +
            t7 * t45 * t47 * t48 * t73 / 2.0F) -
           t9 * t42 * t47 * t48 * t73 / 2.0F) +
          t16 * t123 / 2.0F) +
         t13 * t123 / 4.0F) -
        t10 * t123 / 4.0F;
  t4 = (((((t6 * t46 * t47 * t73 - t5 * t46 * t47 * t73) +
           t2 * t45 * t47 * t48 * t73 / 2.0F) -
          t4 * t42 * t47 * t48 * t73 / 2.0F) +
         t16 * t122 / 2.0F) +
        t13 * t122 / 4.0F) -
       t10 * t122 / 4.0F;
  t264_tmp = t35 * t73;
  t10 = (t38 * t43 * t51 * t53 + t75 * t170) + t264_tmp * t212 / 2.0F;
  t265 = t10 * t10;
  t13 = t41 * t43 * t51 * t53 + t75 * t171;
  t266_tmp_tmp = t11 * t73;
  t15 = t266_tmp_tmp * t212;
  t16 = t13 - t15 / 2.0F;
  t267 = 1.0F / t10;
  t298 = 1.0F / (t265 + t16 * t16);
  t300 = -(atan2f(t13 - t15 * 0.5F, t10) / 2.0F);
  t10 = in1[3] * t41;
  t15 = t73 * t34;
  t338_tmp = t15 * t123;
  t3 = t11 * t75 * t34;
  t2 = in2[1] * t73 * t34;
  t9 = t11 * t83 * t34;
  t7 = t16 * (1.0F / t265);
  t11 = t35 * t75 * t34;
  t8 = in2[0] * t73 * t34;
  t16 = t35 * t83 * t34;
  b_t338_tmp = in1[3] * t42 * t47 * t48 * t73;
  c_t338_tmp = in1[3] * t45 * t47 * t48 * t73;
  d_t338_tmp = t3 * t123;
  e_t338_tmp = t11 * t123;
  t338 = t267 * (((((((((t40 * t41 * t43 * t51 - t90) -
                        t10 * t43 * t52 * t53 * 2.0F) +
                       t10 * t44 * t51 * t53 * -2.0F) -
                      t215) +
                     t338_tmp * t171 / 2.0F) +
                    b_t338_tmp * t212 / 2.0F) +
                   d_t338_tmp * t212 / 4.0F) +
                  t75 * (((-t134 + t135_tmp * t42 * t47 * t48 * t73 / 2.0F) +
                          t2 * t123 / 2.0F) +
                         t9 * t123 / 4.0F)) -
                 t266_tmp_tmp * t12 / 2.0F) +
         t7 * (((((((((-(t38 * t40 * t43 * t51) - t91) +
                      in1[3] * t38 * t43 * t52 * t53 * 2.0F) +
                     t38 * t44 * t53 * t58) +
                    t214) -
                   t338_tmp * t170 / 2.0F) +
                  c_t338_tmp * t212 / 2.0F) +
                 e_t338_tmp * t212 / 4.0F) +
                t75 * (((t132 + t135_tmp * t45 * t47 * t48 * t73 / 2.0F) -
                        t8 * t123 / 2.0F) +
                       t16 * t123 / 4.0F)) -
               t264_tmp * t12 / 2.0F);
  t335_tmp = t15 * t119;
  t10 = in1[0] * t43 * t51 * t53;
  b_t335_tmp = in1[1] * t42 * t46 * t49 * t73;
  c_t335_tmp = in1[1] * t45 * t46 * t49 * t73;
  d_t335_tmp = t3 * t119;
  e_t335_tmp = t11 * t119;
  t278 = t267 * ((((((((t92 - t39 * t41 * t43 * t51) +
                       in1[1] * t41 * t43 * t52 * t53 * 2.0F) +
                      t213) +
                     t335_tmp * t171 / 2.0F) -
                    b_t335_tmp * t212 / 2.0F) +
                   d_t335_tmp * t212 / 4.0F) +
                  t75 * (((t129 - t132_tmp * t42 * t46 * t49 * t73 / 2.0F) +
                          t2 * t119 / 2.0F) +
                         t9 * t119 / 4.0F)) +
                 t266_tmp_tmp * t278 / 2.0F) -
         t7 * ((((((((-(t38 * t39 * t43 * t51) - t10) +
                     in1[1] * t38 * t43 * t52 * t53 * 2.0F) +
                    t216) +
                   t335_tmp * t170 / 2.0F) +
                  c_t335_tmp * t212 / 2.0F) -
                 e_t335_tmp * t212 / 4.0F) +
                t75 * (((t135 + t132_tmp * t45 * t46 * t49 * t73 / 2.0F) +
                        t8 * t119 / 2.0F) -
                       t16 * t119 / 4.0F)) -
               t264_tmp * t278 / 2.0F);
  t132_tmp = t15 * t120;
  t119 = in1[2] * t42 * t46 * t49 * t73;
  t40 = in1[2] * t45 * t46 * t49 * t73;
  t39 = t3 * t120;
  t336_tmp = t11 * t120;
  t58 = t267 * ((((((((-(t37 * t41 * t43 * t51) - t10) +
                      in1[2] * t41 * t43 * t52 * t53 * 2.0F) +
                     t216) +
                    t132_tmp * t171 / 2.0F) -
                   t119 * t212 / 2.0F) +
                  t39 * t212 / 4.0F) +
                 t75 * (((t135 - t134_tmp * t42 * t46 * t49 * t73 / 2.0F) +
                         t2 * t120 / 2.0F) +
                        t9 * t120 / 4.0F)) -
                t266_tmp_tmp * t279 / 2.0F) -
        t7 * ((((((((-(t37 * t38 * t43 * t51) - t92) +
                    in1[2] * t38 * t43 * t52 * t53 * 2.0F) +
                   t132_tmp * t170 / 2.0F) -
                  t213) +
                 t40 * t212 / 2.0F) -
                t336_tmp * t212 / 4.0F) +
               -t75 * (((t129 - t134_tmp * t45 * t46 * t49 * t73 / 2.0F) -
                        t8 * t120 / 2.0F) +
                       t16 * t120 / 4.0F)) +
              t264_tmp * t279 / 2.0F);
  t10 = in1[0] * t41;
  t13 = in1[0] * t38;
  t83 = t15 * t122;
  t135_tmp = in1[0] * t42 * t47 * t48 * t73;
  t123 = in1[0] * t45 * t47 * t48 * t73;
  t6 = t3 * t122;
  t5 = t11 * t122;
  t10 = t267 * (((((((((t36 * t41 * t43 * t51 + t91) -
                       t10 * t43 * t52 * t53 * 2.0F) +
                      t10 * t44 * t51 * t53 * -2.0F) -
                     t214) +
                    t83 * t171 / 2.0F) +
                   t135_tmp * t212 / 2.0F) +
                  t6 * t212 / 4.0F) +
                 t75 * (((-t132 + t129_tmp * t42 * t47 * t48 * t73 / 2.0F) +
                         t2 * t122 / 2.0F) +
                        t9 * t122 / 4.0F)) -
                t266_tmp_tmp * t4 / 2.0F) -
        t7 * (((((((((t36 * t38 * t43 * t51 + t90) -
                     t13 * t43 * t52 * t53 * 2.0F) +
                    t13 * t44 * t51 * t53 * -2.0F) +
                   t215) +
                  t83 * t170 / 2.0F) -
                 t123 * t212 / 2.0F) -
                t5 * t212 / 4.0F) +
               t75 * (((t134 - t129_tmp * t45 * t47 * t48 * t73 / 2.0F) +
                       t8 * t122 / 2.0F) -
                      t16 * t122 / 4.0F)) +
              t264_tmp * t4 / 2.0F);
  t4 = cosf(t300 + 0.785398185F);
  t3 = sinf(t300 + 0.785398185F);
  t7 = t214_tmp * t4;
  t8 = t216_tmp * t4;
  t9 = t213_tmp * t3;
  t2 = t215_tmp * t3;
  t34 = t75 * t265 * t298;
  t35 = t34 * t3;
  fv[0] = t83 * t4 / 2.0F + t35 * t10 / 2.0F;
  t12 = t266_tmp_tmp * t265 * t298;
  t15 = t264_tmp * t265 * t298;
  t16 = t12 * t3;
  t11 = t15 * t4;
  fv[1] = ((((((-t7 + t2) + t135_tmp * t4 / 2.0F) - t123 * t3 / 2.0F) +
             t6 * t4 / 4.0F) -
            t5 * t3 / 4.0F) -
           t16 * t10 / 4.0F) -
          t11 * t10 / 4.0F;
  t12 *= t4;
  t15 *= t3;
  t13 = -(t215_tmp * t4) - t214_tmp * t3;
  fv[2] =
      (((((t13 + t135_tmp * t3 / 2.0F) + t123 * t4 / 2.0F) + t6 * t3 / 4.0F) +
        t5 * t4 / 4.0F) +
       t12 * t10 / 4.0F) -
      t15 * t10 / 4.0F;
  t34 *= t4;
  fv[3] = t83 * t3 / 2.0F - t34 * t10 / 2.0F;
  fv[4] = t335_tmp * t4 * -0.5F - t35 * t278 / 2.0F;
  t10 = -(t213_tmp * t4) - t216_tmp * t3;
  fv[5] = (((((t10 + b_t335_tmp * t4 / 2.0F) - c_t335_tmp * t3 / 2.0F) -
             d_t335_tmp * t4 / 4.0F) +
            e_t335_tmp * t3 / 4.0F) +
           t16 * t278 / 4.0F) +
          t11 * t278 / 4.0F;
  fv[6] = ((((((t8 - t9) + b_t335_tmp * t3 / 2.0F) + c_t335_tmp * t4 / 2.0F) -
             d_t335_tmp * t3 / 4.0F) -
            e_t335_tmp * t4 / 4.0F) -
           t12 * t278 / 4.0F) +
          t15 * t278 / 4.0F;
  fv[7] = t335_tmp * t3 * -0.5F + t34 * t278 / 2.0F;
  fv[8] = t132_tmp * t4 * -0.5F - t35 * t58 / 2.0F;
  fv[9] = ((((((-t8 + t9) + t119 * t4 / 2.0F) - t40 * t3 / 2.0F) -
             t39 * t4 / 4.0F) +
            t336_tmp * t3 / 4.0F) +
           t16 * t58 / 4.0F) +
          t11 * t58 / 4.0F;
  fv[10] = (((((t10 + t119 * t3 / 2.0F) + t40 * t4 / 2.0F) - t39 * t3 / 4.0F) -
             t336_tmp * t4 / 4.0F) -
            t12 * t58 / 4.0F) +
           t15 * t58 / 4.0F;
  fv[11] = t132_tmp * t3 * -0.5F + t34 * t58 / 2.0F;
  fv[12] = t338_tmp * t4 / 2.0F + t35 * t338 / 2.0F;
  fv[13] = (((((t13 + b_t338_tmp * t4 / 2.0F) - c_t338_tmp * t3 / 2.0F) +
              d_t338_tmp * t4 / 4.0F) -
             e_t338_tmp * t3 / 4.0F) -
            t16 * t338 / 4.0F) -
           t11 * t338 / 4.0F;
  fv[14] = ((((((t7 - t2) + b_t338_tmp * t3 / 2.0F) + c_t338_tmp * t4 / 2.0F) +
              d_t338_tmp * t3 / 4.0F) +
             e_t338_tmp * t4 / 4.0F) +
            t12 * t338 / 4.0F) -
           t15 * t338 / 4.0F;
  fv[15] = t338_tmp * t3 / 2.0F - t34 * t338 / 2.0F;
  i = 0;
  i1 = 0;
  for (i2 = 0; i2 < 16; i2++) {
    stateJq[i1 + (i << 2)] = fv[i2];
    i++;
    if (i > 3) {
      i = 0;
      i1++;
    }
  }
}
